[colors]

foreground = "#ECE1D7"
background = "#292522"
cursor_bg = "#ECE1D7"
# cursor_fg = "#000000"
cursor_border = "#ECE1D7"
scrollbar_thumb = "#867462"
split = "#C1A78E"
compose_cursor = "#FFBF00"
visual_bell = "#8B7449"

ansi = [
	'#292522',
	'#BD8183',
	'#78997A',
	'#E49B5D',
	'#7F91B2',
	'#B380B0',
	'#7B9695',
	'#C1A78E',
]

# Darker Colors, harder to look at with dark/transparent backgrounds
# ansi = [
# 	'#292522',
# 	'#7D2A2F',
# 	'#233524',
# 	'#8B7449',
# 	'#273142',
# 	'#422274',
# 	'#253333',
# 	'#403A36',
# ]

brights = [
	'#867462',
	'#D47766',
	'#85B695',
	'#EBC06D',
	'#A3A9CE',
	'#CF9BC2',
	'#89B3B6',
	'#ECE1D7',
]


[colors.indexed]

[colors.tab_bar]
background = '#867462'
[colors.tab_bar.active_tab]
bg_color = '#403A36'
fg_color = "#ECE1D7"
# For reference/customization, copied from Bamboo. Options apply to active_tab, inactive_tab, inactive_tab_hover, new_tab, new_tab_hover
# fg_color = "#111210"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
[colors.tab_bar.inactive_tab]
bg_color = '#292522'
fg_color = "#ECE1D7"
[colors.tab_bar.new_tab]
bg_color = "#8B7449"
fg_color = "#ECE1D7"
[colors.tab_bar.new_tab_hover]
bg_color = "#253333"
fg_color = "#ECE1D7"

[metadata]
aliases = []
author = "LumenLuminis"
name = "Melangely-Faithful"
origin_url = "https://github.com/LumenLuminis/Melangely-Faithful-Wezterm"
wezterm_version = "20240203-110809-5046fc22"
